# Generated by Django 3.2.7 on 2021-10-10 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ampurcode', models.CharField(max_length=2)),
                ('ampurname', models.CharField(max_length=155)),
                ('ampurcodefull', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Cchangwat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changwatcode', models.CharField(max_length=2)),
                ('changwatname', models.CharField(max_length=155)),
                ('zonecode', models.CharField(max_length=2)),
                ('changwatname_en', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Savechumphon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('1', 'ชาย'), ('2', 'หญิง')], default='ชาย', max_length=10)),
                ('age', models.IntegerField()),
                ('id_card', models.CharField(max_length=15)),
                ('mobile_phone', models.CharField(max_length=10)),
                ('mobile_partner', models.CharField(blank=True, max_length=10, null=True)),
                ('date_arrive', models.DateField()),
                ('close_contact', models.CharField(choices=[('1', 'เคยใกล้ชิด'), ('2', 'ไม่เคยใกล้ชิด')], default='ไม่เคยใกล้ชิด', max_length=25)),
                ('sign', models.CharField(default='ไม่มีอาการ', max_length=25)),
                ('history', models.CharField(default='ไม่เคย', max_length=25)),
                ('moo', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.CharField(max_length=255)),
                ('between', models.CharField(choices=[('1', 'ประจวบคีรีขันธ์'), ('2', 'ระนอง'), ('3', 'สุราษฎร์ธานี')], max_length=155)),
                ('stay', models.IntegerField()),
                ('duty_place', models.TextField()),
                ('vaccine_pic', models.ImageField(default='default.jpg', upload_to='vaccine_pic')),
                ('sickness', models.ImageField(default='default.jpg', upload_to='sickness')),
                ('lab', models.ImageField(default='default.jpg', upload_to='lab')),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Cchangwat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.cchangwat')),
                ('ampur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.campur')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.duty')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.occupation')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.reason')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.travel')),
                ('vaccinate1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.vaccine1')),
                ('vaccinate2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.vaccine2')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Ctambon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamboncode', models.CharField(max_length=2)),
                ('tambonname', models.CharField(max_length=155)),
                ('tamboncodefull', models.CharField(max_length=6)),
                ('ampurcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.campur')),
                ('changwatcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.cchangwat')),
            ],
        ),
        migrations.AddField(
            model_name='campur',
            name='changwatcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savechumphon.cchangwat'),
        ),
    ]
